In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [13]:
# Get Type
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('float64')

In [16]:
# Get Size
a.itemsize

4

In [20]:
b.itemsize

8

In [18]:
# Get total size
a.size * a.itemsize

12

In [19]:
a.nbytes

12