In [1]:
import numpy as np

In [5]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [8]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [10]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.97861251, 0.5323382 ],
       [0.12868708, 0.19643002],
       [0.17213692, 0.34328272],
       [0.00152949, 0.67690813]])

In [12]:
np.random.random_sample(a.shape)

array([[0.8534496 , 0.08752766, 0.58491302, 0.74928952, 0.85929917,
        0.39349599, 0.63191371],
       [0.39624101, 0.60810434, 0.74393219, 0.86907944, 0.00590602,
        0.8133379 , 0.82608651]])

In [46]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  0,  6],
       [ 6, -2,  4],
       [ 0, -2, -3]])

In [47]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [58]:
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays~!

In [59]:
a = np.array([1,2,3])
a


array([1, 2, 3])

In [61]:
b = a
b

array([1, 2, 3])

In [62]:
b[0] = 100
print(b)

[100   2   3]


In [63]:
print(a)

[100   2   3]


In [64]:
b = a.copy()
b[0] = 1
print(b)
print(a)

[1 2 3]
[100   2   3]
