### Linear Algebra

In [2]:
import numpy as np

In [7]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [12]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [13]:
c = np.identity(3)

In [14]:
# Find the determinant
np.linalg.det(c)

1.0

### Reference docs (https://numpy.org/doc/stable/reference/routines.linalg.html)

Determinant  
Trace 
Singular Vector Decomposition  
Eigenvalues  
Matrix Norm  
Inverse  
Etc...  