Mathmatics

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a += 2
a

array([5, 6, 7, 8])

In [10]:
b = np.array([1,0,1,0])
a + b

array([6, 6, 8, 8])

In [11]:
a ** 2

array([25, 36, 49, 64])

In [12]:
# Take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [13]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

For a lot more (https://numpy.org/doc/stable/reference/routines.math.html)