### Statistics

In [1]:
import numpy as np

In [2]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.min(stats)

1

In [3]:
np.min(stats, axis=1)

array([1, 4])

In [4]:
np.max(stats)

6

In [6]:
np.max(stats,axis=1)

array([3, 6])

In [7]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [8]:
np.sum(stats, axis=1)

array([ 6, 15])